### ISSUE TITLE
Build error for freebsd

### ISSUE THREAD

**Issue by timukas** [MythicAgents/merlin#21] opened 2024-09-05 14:09 UTC
Hi,

Latest Mythic with latest merlin agent fires an error when building default payload for freebsd:

```
Status	 Error
Step Output	# github.com/Ne0nd0g/merlin-agent/v2/commands
/go/pkg/mod/github.com/!ne0nd0g/merlin-agent/v2@v2.4.1/commands/shell_freebsd.go:36:12: undefined: fmt
Step Error	exit status 1
```

Any hints/ideas how to fix it?

**Comment by Ne0nd0g** [comment] 2024-09-05 14:42
Is this the same issue as https://github.com/MythicAgents/merlin/issues/17 ?

**Comment by timukas** [comment] 2024-09-05 16:52
Yes, looks like same.

**Comment by Ne0nd0g** [comment] 2024-09-06 12:28
Closing because it is a duplicate of #17

**Closed as completed by Ne0nd0g** 2024-09-06 12:28 UTC
